---
layout: post
title: 자바 예외처리
categories: [Java]
tags: [Java]
description: 자바에서의 예외처리(exception handling)에 대해 알아보자
comments: true
---
# **예외처리(exception handling)**  
### 1. 프로그램 오류  
프로그램이 실행 중 어떤 원인에 의해 오작동을 하거나 비정상적으로 종료되는 경우가 있는데, 이러한 결과를 초래하는 원인을 프로그램 에러 또는 오류라고 한다.
이를 발생시점에 따라 '컴파일 에러'와 '런타임 에러'로 나눌 수 있는데, 컴파일 에러는 컴파일 할 때 발생하는 에러이고 프로그램의 실행도중에 발생하는 에러를 '런타임 에러'라고 한다. 이 외에도 '논리적 에러'가 있느데, 컴파일도 잘되고 실행도 잘되지만 의도한 것과 다르게 동작하는 것을 말한다.

소스코드를 컴파일하면 컴파일러가 소스코드에 대해 오타나 잘못된 구문, 자료형 체크 등의 기본적인 검사를 수행하여 오류가 있는지를 알려 준다. 컴파일러가 알려 준 에러들을 모두 수정해서 컴파일을 성공적으로 마치고 나면, 클래스 파일이 생성되고, 생성된 클래스 파일을 실행할 수 있게 되는 것이다.
하지만 컴파일을 에러없이 성공적으로 마쳐도 실행시 에러가 발생하지 않는 것은 아니다. 컴파일러가 실행도중에 발생할 수 있는 잠재적인 오류까지 검사할 수 없기 때문에 컴파일은 잘되었어도 실행 중 에러에 의해 잘못된 결과를 얻거나  프로그램이 비정상적으로 종료될 수 있다.

런타임 에러를 방지하기 위해서는 프로그램의 실행도중 발생할 수 있는 모든 경우의 수를 고려하여 이에대한 대비를 하는 것이 필요한데, 자바에서는 실행시 발생할 수 있는 프로그램 오류를 '에러'와 '예외' 두 가지로 구분하였다. 에러는 메모리 부족이나 스택오버플로우와 같이 발생하면 복구할 수 없는 심각한 오류이고, 예외는 발생하더라도 수습될 수 있는 에러에 비해 비교적 덜 심각한 것이다.  
<br>  
### 2. try-catch문으로 예외처리하기  
프로그램 실행도중 발생하는 에러는 어쩔 수 없지만, 예외는 프로그래머리가 직접 미리 처리해주어야 한다. 예외처리란 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것이며, 예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 갑작스럼 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것이다.

발생한 예외를 처리하지 못하면, 프로그램은 비정상적으로 종료되며, 처리되지 못한 예외는 JVM의 '예외처리기'가 받아서 예외의 원인을 화면에 출력한다. 예외를 처리하기 위해 사용되는 try-catch문의 구조는 다음과 같다.  
~~~
try {
	// 예외가 발생할 가능성이 있는 문장
} catch (Exception1 e1) {
	// Exception1이 발생했을 경우 이를 처리하기 위한 문장
} catch (Exception2 e2) {
	// Exception2이 발생했을 경우 이를 처리하기 위한 문장
}
~~~  
하나의 try블럭 다음에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch블럭이 올 수 있으며, 이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch블럭만 수행된다. 발생한 예외의 종류와 일치하는 catch블럭이 없으면 예외는 처리되지 않는다.  
~~~java
class Main {
	public static void main(String[] args) {
		int x = 100;
		int y = 0;

		for (int i = 0; i < 10; i++) {
			try {
				y = x / (int) (Math.random() * 10);
				System.out.println(y);
			} catch (Exception e) {
				System.out.println("error");
			}
		}
	}
}
~~~  
위 예제는 간단한 try-catch문의 예제이다 변수 x에 저장되어있는 값100을 0~9사이의 임의의 정수로 나눈 결과를 출력하는 일을 10번 반복한다. 매번 실행할때 마다 결과가 다른데, 정수를 0으로 나누고자할때 에러가 발생하므로 'error'이라는 문구가 출력되는 예제이다.
